version: 0.2

phases:
  pre_build:
    commands:
      - echo PreBuild Started ...
      - aws --version
      - docker --version
      - aws ecr-public  get-login-password  --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws/p2e3u7x0
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t pension-detail-service .
      - docker tag pension-detail-service public.ecr.aws/p2e3u7x0/841331-pension-detail-service:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push public.ecr.aws/p2e3u7x0/841331-pension-detail-service:latest
      - echo Writing definition files
      - printf '[{"name":"841331-pension-detail-service","imageUri":"%s"}]'  public.ecr.aws/p2e3u7x0/841331-pension-detail-service:latest > imageDefinition.json

artifacts:
  files: 
    - imageDefinition.json
